### ISSUE TITLE
Getting error Error: Cannot find module 'oracledb', when i try run command Node server.js

### ISSUE THREAD

**Issue by ashdens5146** [oracle/learning-library#777]
throw err;
    ^

Error: Cannot find module 'oracledb'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/opc/ATPnodeapp/server.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by joseleneneng** [comment]
npm install oracledb

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
